import {
    Editor,
    FormattingPlugin,
    UndoRedoPlugin,
    ListsPlugin,
    ColorPlugin,
    LinksPlugin,
    MediaPlugin,
    DirectionalityPlugin,
    AlignmentPlugin,
    TablesPlugin,
    AccordionPlugin,
    PageBreakPlugin,
    TocPlugin,
    PasteImagePlugin,
    MentionsPlugin,
    CodeBlockPlugin,
    DateTimePlugin,
    EmojiPlugin,
    TokensPlugin,
    PasteCleanupPlugin,
    FontSizePlugin,
    SpacingPlugin,
    ButtonBlockPlugin,
    ImageResizePlugin,
    PreviewPlugin,
    SourceCodePlugin,
    FontFamilyPlugin,
    BlockQuotePlugin,
    FindReplacePlugin,
    WordCountPlugin
} from './index';

const editor = new Editor('#editor', [
    FormattingPlugin,
    UndoRedoPlugin,
    ListsPlugin,
    ColorPlugin,
    DirectionalityPlugin,
    AlignmentPlugin,
    LinksPlugin,
    MediaPlugin,
    TablesPlugin,
    AccordionPlugin,
    PageBreakPlugin,
    TocPlugin,
    PasteImagePlugin,
    MentionsPlugin,
    CodeBlockPlugin,
    DateTimePlugin,
    EmojiPlugin,
    TokensPlugin,
    PasteCleanupPlugin,
    FontSizePlugin,
    SpacingPlugin,
    ButtonBlockPlugin,
    ImageResizePlugin,
    PreviewPlugin,
    SourceCodePlugin,
    FontFamilyPlugin,
    BlockQuotePlugin,
    FindReplacePlugin,
    WordCountPlugin
]);

// Just for testing the public api
document.getElementById('get-content')?.addEventListener('click', () => {
    console.log(editor.getContent());
    alert(editor.getContent());
});
